package com.wlvpn.consumervpn.presentation.di.provider

import android.content.res.Resources
import com.netprotect.licenses.application.value.SoftwareLicense
import com.netprotect.licenses.implementation.input.LicensesInputLocator
import com.wlvpn.consumervpn.R.string
import io.reactivex.Maybe

class LocalLicensesInputLocator(
    private val resources: Resources
) : LicensesInputLocator {

    override fun getSoftwareLicenses(): Maybe<List<SoftwareLicense>> {

        val softwareLicenses = mutableListOf<SoftwareLicense>()

        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_open_vpn_name),
                resources.getString(string.licenses_label_open_vpn_copyright),
                listOf(resources.getString(string.licenses_label_gpl_2_0_license)),
                resources.getString(string.licenses_label_open_vpn_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_strong_swan_name),
                resources.getString(string.licenses_label_strong_swan_copyright),
                listOf(resources.getString(string.licenses_label_gpl_2_0_license)),
                resources.getString(string.licenses_label_strong_swan_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_fresco_name),
                resources.getString(string.licenses_label_fresco_copyright),
                listOf(resources.getString(string.licenses_label_mit_license)),
                resources.getString(string.licenses_label_fresco_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_androidx_name),
                resources.getString(string.licenses_label_androidx_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_androidx_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_gson_name),
                resources.getString(string.licenses_label_gson_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_gson_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_retrofit_name),
                resources.getString(string.licenses_label_retrofit_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_retrofit_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_junit_name),
                resources.getString(string.licenses_label_junit_copyright),
                listOf(resources.getString(string.licenses_label_epl_license)),
                resources.getString(string.licenses_label_junit_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_mockito_name),
                resources.getString(string.licenses_label_mockito_copyright),
                listOf(resources.getString(string.licenses_label_mit_license)),
                resources.getString(string.licenses_label_mockito_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_timber_name),
                resources.getString(string.licenses_label_timber_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_tmber_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_okhttp_name),
                resources.getString(string.licenses_label_okhttp_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_okhtpp_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_apache_commons_name),
                resources.getString(string.licenses_label_apache_commons_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_apache_commons_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_rxjava_name),
                resources.getString(string.licenses_label_rxjava_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_rxjava_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_rxandroid_name),
                resources.getString(string.licenses_label_rxandroid_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_rxandroid_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_dagger_name),
                resources.getString(string.licenses_label_dagger_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_dagger_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_logan_square_name),
                resources.getString(string.licenses_label_logan_square_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_logan_square_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_rxbinding_name),
                resources.getString(string.licenses_label_rxbinding_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_rxbinding_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_android_pathview_name),
                resources.getString(string.licenses_label_android_pathview_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_android_pathview_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_calligraphy_name),
                resources.getString(string.licenses_label_calligraphy_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_calligraphy_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_jackson_jaxrs_providers_name),
                resources.getString(string.licenses_label_jackson_jaxrs_providers_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_jackson_jaxrs_providers_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_slf4j_name),
                resources.getString(string.licenses_label_slf4j_copyright),
                listOf(resources.getString(string.licenses_label_mit_license)),
                resources.getString(string.licenses_label_slf4j_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_logback_name),
                resources.getString(string.licenses_label_logback_copyright),
                listOf(
                    resources.getString(string.licenses_label_epl_license),
                    resources.getString(string.licenses_label_lgpl_2_1_license)
                ),
                resources.getString(string.licenses_label_logback_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_autovalue_name),
                resources.getString(string.licenses_label_autovalue_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_autovalue_website)
            )
        )
        softwareLicenses.add(
            SoftwareLicense(
                resources.getString(string.licenses_label_leakcanary_name),
                resources.getString(string.licenses_label_leakcanary_copyright),
                listOf(resources.getString(string.licenses_label_apache_2_license)),
                resources.getString(string.licenses_label_leakcanary_website)
            )
        )
        return Maybe.just(softwareLicenses)
    }
}
